[tool.black]
line-length = 120
target-version = ['py38']

# regex
exclude = '''
/(
  \.git |
  \.mypy_cache |
  \.?venv |
  plugin/libs |
  tests/files |
  stubs |
  typings
)/
'''

[tool.pyright]
include = ["./"]
exclude = [
  "**/__pycache__/",
  "**/node_modules/",
  # git-related
  "**/.git/",
  "**/br-*/",
  "**/branch-*/",
]
ignore = [
  "**/.venv",
  "plugin/libs/",
]
stubPath = "typings"
pythonVersion = "3.8"
